In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("C:/Users/PREET/OneDrive/Desktop/Tamil_nadu_taxi_trips_.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1491 entries, 0 to 1490
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date_Time             1491 non-null   object
 1   Pickup_Location       1491 non-null   object
 2   Drop_Location         1491 non-null   object
 3   Distance_km           1444 non-null   float64
 4   Fare_INR              1427 non-null   float64
 5   No_of_Passengers      1457 non-null   float64
 6   Travel_Time_hrs       1473 non-null   float64
 7   Tips_INR              1471 non-null   float64
 8   Tourist_Place_Nearby  1491 non-null   object
 9   Weather_Condition     1472 non-null   object
 10  Vehicle_Type          1485 non-null   object
dtypes: float64(5), object(6)
memory usage: 128.3+ KB

In [7]:
df.head(1300)

,Date_Time,Pickup_Location,Drop_Location,Distance_km,Fare_INR,No_of_Passengers,Travel_Time_hrs,Tips_INR,Tourist_Place_Nearby,Weather_Condition,Vehicle_Type
0,25-10-2011 22:58,Namakkal,Krishnagiri,65.8,1076.40,6.0,1.32,113.49,Krishnagiri Dam,Windy,Hatchback
1,03-01-2014 10:11,Ramanathapuram,Nagapattinam,NaN,1298.39,4.0,2.85,171.95,Velankanni Church,Rainy,SUV
2,26-07-2011 10:06,Tirunelveli,Thanjavur,121.7,1869.84,1.0,2.21,168.59,Brihadeeswara Temple,Rainy,Auto
3,25-08-2011 19:16,Karur,Namakkal,176.7,2828.04,3.0,2.81,0.00,Namakkal Fort,Rainy,SUV
4,07-08-2013 18:29,Namakkal,Theni,281.2,4100.53,NaN,5.66,432.56,Suruli Falls,Windy,SUV
...,...,...,...,...,...,...,...,...,...,...,...
1295,15-04-2010 05:42,Cuddalore,Karur,54.7,828.20,1.0,1.47,89.72,Kalyana Venkataramanaswamy Temple,Sunny,Auto
1296,07-11-2012 01:45,Karur,Theni,46.3,652.48,3.0,0.92,70.07,Suruli Falls,Windy,SUV
1297,28-03-2015 23:48,Thanjavur,Coimbatore,194.7,3045.55,2.0,4.72,0.00,Isha Yoga Center,Cloudy,Hatchback
1298,10-09-2017 20:47,Erode,Krishnagiri,166.4,2336.61,4.0,3.87,0.00,Krishnagiri Dam,Sunny,Sedan
1299,29-08-2013 20:35,Cuddalore,Tiruppur,36.5,488.49,2.0,0.65,68.20,Sivanmalai Murugan Temple,Cloudy,Auto

In [9]:
df.shape

(1491, 11)

In [10]:
df.columns

Index(['Date_Time', 'Pickup_Location', 'Drop_Location', 'Distance_km',
       'Fare_INR', 'No_of_Passengers', 'Travel_Time_hrs', 'Tips_INR',
       'Tourist_Place_Nearby', 'Weather_Condition', 'Vehicle_Type'],
      dtype='object')

In [11]:
df.index

RangeIndex(start=0, stop=1491, step=1)

In [12]:
df.tail()

,Date_Time,Pickup_Location,Drop_Location,Distance_km,Fare_INR,No_of_Passengers,Travel_Time_hrs,Tips_INR,Tourist_Place_Nearby,Weather_Condition,Vehicle_Type
1486,11-04-2010 22:48,Nagapattinam,Thanjavur,205.3,3096.91,4.0,6.57,209.85,Brihadeeswara Temple,Sunny,Auto
1487,30-09-2011 22:30,Namakkal,Chennai,136.6,2227.24,3.0,2.04,0.00,Marina Beach,Sunny,Mini Van
1488,18-10-2015 07:28,Dharmapuri,Karur,107.9,1515.77,4.0,2.49,0.00,Kalyana Venkataramanaswamy Temple,Windy,Mini Van
1489,07-12-2015 18:39,Pudukkottai,Chennai,41.7,734.25,3.0,0.90,0.00,Marina Beach,Cloudy,Mini Van
1490,09-08-2018 22:29,Sivaganga,Erode,221.8,3959.42,5.0,3.86,0.00,Bhavani Sangameswarar Temple,Cloudy,Sedan

In [13]:
df.describe()

,Distance_km,Fare_INR,No_of_Passengers,Travel_Time_hrs,Tips_INR
count,1444.000000,1427.000000,1457.000000,1473.000000,1471.000000
mean,155.199169,2339.990960,3.481126,3.267101,93.775765
std,84.732445,1317.100111,1.726437,2.011627,174.946411
min,10.000000,136.850000,1.000000,0.170000,0.000000
25%,82.225000,1202.535000,2.000000,1.660000,0.000000
50%,156.150000,2326.590000,3.000000,3.080000,0.000000
75%,228.575000,3417.350000,5.000000,4.580000,121.895000
max,299.700000,5301.510000,6.000000,9.540000,976.550000

In [14]:
df ['Drop_Location']

0        Krishnagiri
1       Nagapattinam
2          Thanjavur
3           Namakkal
4              Theni
            ...
1486       Thanjavur
1487         Chennai
1488           Karur
1489         Chennai
1490           Erode
Name: Drop_Location, Length: 1491, dtype: object

In [16]:
df.loc[0]

Date_Time               25-10-2011 22:58
Pickup_Location                 Namakkal
Drop_Location                Krishnagiri
Distance_km                         65.8
Fare_INR                          1076.4
No_of_Passengers                     6.0
Travel_Time_hrs                     1.32
Tips_INR                          113.49
Tourist_Place_Nearby     Krishnagiri Dam
Weather_Condition                  Windy
Vehicle_Type                   Hatchback
Name: 0, dtype: object

In [18]:
df.iloc[1]

Date_Time                03-01-2014 10:11
Pickup_Location            Ramanathapuram
Drop_Location                Nagapattinam
Distance_km                           NaN
Fare_INR                          1298.39
No_of_Passengers                      4.0
Travel_Time_hrs                      2.85
Tips_INR                           171.95
Tourist_Place_Nearby    Velankanni Church
Weather_Condition                   Rainy
Vehicle_Type                          SUV
Name: 1, dtype: object

In [19]:
df.loc[0:2]

,Date_Time,Pickup_Location,Drop_Location,Distance_km,Fare_INR,No_of_Passengers,Travel_Time_hrs,Tips_INR,Tourist_Place_Nearby,Weather_Condition,Vehicle_Type
0,25-10-2011 22:58,Namakkal,Krishnagiri,65.8,1076.40,6.0,1.32,113.49,Krishnagiri Dam,Windy,Hatchback
1,03-01-2014 10:11,Ramanathapuram,Nagapattinam,NaN,1298.39,4.0,2.85,171.95,Velankanni Church,Rainy,SUV
2,26-07-2011 10:06,Tirunelveli,Thanjavur,121.7,1869.84,1.0,2.21,168.59,Brihadeeswara Temple,Rainy,Auto

In [26]:
df[df['Distance_km'] > 280]

,Date_Time,Pickup_Location,Drop_Location,Distance_km,Fare_INR,No_of_Passengers,Travel_Time_hrs,Tips_INR,Tourist_Place_Nearby,Weather_Condition,Vehicle_Type
4,07-08-2013 18:29,Namakkal,Theni,281.2,4100.53,NaN,5.66,432.56,Suruli Falls,Windy,SUV
50,28-11-2013 15:01,Salem,Karur,299.7,5301.51,NaN,6.25,0.00,Kalyana Venkataramanaswamy Temple,Rainy,Hatchback
58,28-05-2016 15:05,Thanjavur,Erode,291.6,4872.34,4.0,5.33,780.62,Bhavani Sangameswarar Temple,Cloudy,Auto
62,06-01-2010 17:23,Tirunelveli,Vellore,299.0,5095.89,3.0,7.28,829.20,Vellore Fort,Windy,SUV
87,29-05-2013 00:11,Kanyakumari,Villupuram,289.5,4731.42,6.0,5.91,0.00,Gingee Fort,Windy,Sedan
...,...,...,...,...,...,...,...,...,...,...,...
1345,17-05-2016 21:07,Madurai,Nagapattinam,298.5,3587.24,6.0,4.95,250.12,Velankanni Church,Rainy,Hatchback
1357,30-11-2016 19:22,Erode,Villupuram,281.7,4911.95,3.0,4.04,0.00,Gingee Fort,Sunny,Auto
1376,22-12-2011 04:37,Nagapattinam,Erode,297.1,4656.56,1.0,4.47,0.00,Bhavani Sangameswarar Temple,Rainy,SUV
1437,09-06-2010 05:55,Thanjavur,Madurai,297.2,4718.41,4.0,7.07,0.00,Meenakshi Temple,Windy,Mini Van
1465,18-02-2013 17:53,Pudukkottai,Tirunelveli,299.6,3827.04,1.0,8.03,0.00,Courtallam Falls,Cloudy,SUV

In [33]:
df[(df['Distance_km'] > 280) & (df['Pickup_Location'] == 'Thanjavur')]

,Date_Time,Pickup_Location,Drop_Location,Distance_km,Fare_INR,No_of_Passengers,Travel_Time_hrs,Tips_INR,Tourist_Place_Nearby,Weather_Condition,Vehicle_Type
58,28-05-2016 15:05,Thanjavur,Erode,291.6,4872.34,4.0,5.33,780.62,Bhavani Sangameswarar Temple,Cloudy,Auto
936,26-03-2015 20:49,Thanjavur,Chennai,281.3,4212.87,2.0,4.42,0.00,Marina Beach,Windy,Hatchback
1437,09-06-2010 05:55,Thanjavur,Madurai,297.2,4718.41,4.0,7.07,0.00,Meenakshi Temple,Windy,Mini Van

In [34]:
df.drop('Vehicle_Type', axis=1, inplace=True)

In [35]:
df.head()

,Date_Time,Pickup_Location,Drop_Location,Distance_km,Fare_INR,No_of_Passengers,Travel_Time_hrs,Tips_INR,Tourist_Place_Nearby,Weather_Condition
0,25-10-2011 22:58,Namakkal,Krishnagiri,65.8,1076.40,6.0,1.32,113.49,Krishnagiri Dam,Windy
1,03-01-2014 10:11,Ramanathapuram,Nagapattinam,NaN,1298.39,4.0,2.85,171.95,Velankanni Church,Rainy
2,26-07-2011 10:06,Tirunelveli,Thanjavur,121.7,1869.84,1.0,2.21,168.59,Brihadeeswara Temple,Rainy
3,25-08-2011 19:16,Karur,Namakkal,176.7,2828.04,3.0,2.81,0.00,Namakkal Fort,Rainy
4,07-08-2013 18:29,Namakkal,Theni,281.2,4100.53,NaN,5.66,432.56,Suruli Falls,Windy

In [36]:
df.isnull()

,Date_Time,Pickup_Location,Drop_Location,Distance_km,Fare_INR,No_of_Passengers,Travel_Time_hrs,Tips_INR,Tourist_Place_Nearby,Weather_Condition
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
1486,False,False,False,False,False,False,False,False,False,False
1487,False,False,False,False,False,False,False,False,False,False
1488,False,False,False,False,False,False,False,False,False,False
1489,False,False,False,False,False,False,False,False,False,False
1490,False,False,False,False,False,False,False,False,False,False

In [41]:
df.isnull().sum()

Date_Time                0
Pickup_Location          0
Drop_Location            0
Distance_km             47
Fare_INR                64
No_of_Passengers        34
Travel_Time_hrs         18
Tips_INR                20
Tourist_Place_Nearby     0
Weather_Condition       19
dtype: int64

In [45]:
df.fillna(1)

,Date_Time,Pickup_Location,Drop_Location,Distance_km,Fare_INR,No_of_Passengers,Travel_Time_hrs,Tips_INR,Tourist_Place_Nearby,Weather_Condition
0,25-10-2011 22:58,Namakkal,Krishnagiri,65.8,1076.40,6.0,1.32,113.49,Krishnagiri Dam,Windy
1,03-01-2014 10:11,Ramanathapuram,Nagapattinam,1.0,1298.39,4.0,2.85,171.95,Velankanni Church,Rainy
2,26-07-2011 10:06,Tirunelveli,Thanjavur,121.7,1869.84,1.0,2.21,168.59,Brihadeeswara Temple,Rainy
3,25-08-2011 19:16,Karur,Namakkal,176.7,2828.04,3.0,2.81,0.00,Namakkal Fort,Rainy
4,07-08-2013 18:29,Namakkal,Theni,281.2,4100.53,1.0,5.66,432.56,Suruli Falls,Windy
...,...,...,...,...,...,...,...,...,...,...
1486,11-04-2010 22:48,Nagapattinam,Thanjavur,205.3,3096.91,4.0,6.57,209.85,Brihadeeswara Temple,Sunny
1487,30-09-2011 22:30,Namakkal,Chennai,136.6,2227.24,3.0,2.04,0.00,Marina Beach,Sunny
1488,18-10-2015 07:28,Dharmapuri,Karur,107.9,1515.77,4.0,2.49,0.00,Kalyana Venkataramanaswamy Temple,Windy
1489,07-12-2015 18:39,Pudukkottai,Chennai,41.7,734.25,3.0,0.90,0.00,Marina Beach,Cloudy
1490,09-08-2018 22:29,Sivaganga,Erode,221.8,3959.42,5.0,3.86,0.00,Bhavani Sangameswarar Temple,Cloudy

In [40]:
df.dropna()

,Date_Time,Pickup_Location,Drop_Location,Distance_km,Fare_INR,No_of_Passengers,Travel_Time_hrs,Tips_INR,Tourist_Place_Nearby,Weather_Condition
0,25-10-2011 22:58,Namakkal,Krishnagiri,65.8,1076.40,6.0,1.32,113.49,Krishnagiri Dam,Windy
2,26-07-2011 10:06,Tirunelveli,Thanjavur,121.7,1869.84,1.0,2.21,168.59,Brihadeeswara Temple,Rainy
3,25-08-2011 19:16,Karur,Namakkal,176.7,2828.04,3.0,2.81,0.00,Namakkal Fort,Rainy
5,10-12-2017 18:11,Pudukkottai,Dharmapuri,257.3,3265.23,1.0,3.73,0.00,Hogenakkal Falls,Windy
6,18-05-2013 03:02,Chennai,Tiruppur,219.7,3317.63,3.0,3.28,0.00,Sivanmalai Murugan Temple,Windy
...,...,...,...,...,...,...,...,...,...,...
1486,11-04-2010 22:48,Nagapattinam,Thanjavur,205.3,3096.91,4.0,6.57,209.85,Brihadeeswara Temple,Sunny
1487,30-09-2011 22:30,Namakkal,Chennai,136.6,2227.24,3.0,2.04,0.00,Marina Beach,Sunny
1488,18-10-2015 07:28,Dharmapuri,Karur,107.9,1515.77,4.0,2.49,0.00,Kalyana Venkataramanaswamy Temple,Windy
1489,07-12-2015 18:39,Pudukkottai,Chennai,41.7,734.25,3.0,0.90,0.00,Marina Beach,Cloudy
1490,09-08-2018 22:29,Sivaganga,Erode,221.8,3959.42,5.0,3.86,0.00,Bhavani Sangameswarar Temple,Cloudy

In [46]:
df.isnull().sum()

Date_Time                0
Pickup_Location          0
Drop_Location            0
Distance_km             47
Fare_INR                64
No_of_Passengers        34
Travel_Time_hrs         18
Tips_INR                20
Tourist_Place_Nearby     0
Weather_Condition       19
dtype: int64

In [47]:
df.sort_values(by='Pickup_Location')

,Date_Time,Pickup_Location,Drop_Location,Distance_km,Fare_INR,No_of_Passengers,Travel_Time_hrs,Tips_INR,Tourist_Place_Nearby,Weather_Condition
432,21-08-2017 18:12,Chennai,Karur,NaN,1445.79,6.0,1.84,0.00,Kalyana Venkataramanaswamy Temple,Windy
873,15-03-2016 18:37,Chennai,Madurai,156.1,2009.94,4.0,2.75,119.50,Meenakshi Temple,Sunny
1458,21-08-2015 02:37,Chennai,Krishnagiri,155.3,2788.12,2.0,3.85,427.64,Krishnagiri Dam,Windy
1187,02-06-2011 15:23,Chennai,Dharmapuri,219.6,3133.49,5.0,4.74,0.00,Hogenakkal Falls,Windy
810,19-02-2011 05:29,Chennai,Theni,209.3,3209.06,3.0,3.14,238.11,Suruli Falls,Sunny
...,...,...,...,...,...,...,...,...,...,...
669,13-07-2013 09:34,Virudhunagar,Karur,103.6,NaN,1.0,1.93,176.61,Kalyana Venkataramanaswamy Temple,Rainy
1433,24-04-2010 07:26,Virudhunagar,Nagapattinam,11.2,154.36,5.0,0.20,0.00,Velankanni Church,Windy
272,09-02-2017 10:00,Virudhunagar,Namakkal,82.7,1079.48,3.0,2.53,0.00,Namakkal Fort,Sunny
367,10-05-2015 21:52,Virudhunagar,Nagapattinam,30.6,425.23,3.0,0.88,26.52,Velankanni Church,Windy
745,01-06-2013 22:55,Virudhunagar,Villupuram,171.3,2446.98,1.0,2.58,0.00,Gingee Fort,Cloudy